### ISSUE TITLE
Checksum mismatch exception with OTF-font

### ISSUE THREAD

**Issue by geoglis** [xenocrat/sfnt2woff#1]
Hi,

when I try to convert the font **FiraSansCompressed-Light.otf** it gives me the exception "Checksum mismatch in table data."
Following the spec (https://docs.microsoft.com/en-us/typography/opentype/spec/otff) it seems to be a font with sfntVersion 0x4F54544F ('OTTO').

The font can be dowloaded from this site:
https://www.fontsquirrel.com/fonts/fira-sans-compressed

Can U take a look at it, please?

I tried it out with PHP Version 7.3.5 64bit nts.

Swen

**Comment by xenocrat** [comment]
Hello there.

Firstly I'm sorry it's taken me so long to reply to your issue – somehow I managed to unwatch this repo and so didn't see it until now.

The issue appears to be caused by a problem in the checksum calculation that I suspected might occur on 64-bit PHP but I had no way to test. The checksum is calculated by summing the table data in chunks of unsigned 32-bit integers, and PHP's platform-dependent implementation of integers means that might work differently for you than it does for me. For example, on my Windows 32-bit installation the file __firasanscompressed-light.otf__ from your link converts without error.

I've tried to implement a method of doing the calculation using bitwise operations to resolve the issue, but my understanding of PHP's integer implementation is limited. My change certainly doesn't seem to make things worse for me. Maybe it solves your issue as well? You can download the latest from master to test.

**Comment by xenocrat** [comment]
I've done some further work on the problem. I think the latest code in master will work on 64-bit PHP.
